version: '3.8'
services:

  app-layer:
    container_name: app-cnt
    restart: always
    build:
      context: ./
    env_file:
      - .env
    volumes:
    - ./surveys:/usr/src/app/surveys
    ports:
      - 4400:4400

volumes:
  surveys: